services:
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    tty: true
    environment:
      TZ: "Europe/London"
      LANG: "de_DE.UTF-8"
    ports:
      - 3000:3000
    volumes:
      - ./config.yaml:/config.yaml
      # - ./custom.css:/custom.css
    restart: always
