services:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    tty: true
    environment:
      LANG: "en_GB"
      TZ: "Europe/London"
    ports:
      - 3000:3000
    volumes:
      - ./config.yaml:/config.yaml
      # - ./custom.css:/custom.css
    restart: always
