services:
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      KIOSK_DEBUG: false
      TZ: "Europe/London"
    ports:
      - 3000:3000
    volumes:
      - ./config.yaml:/config.yaml
    restart: always
