version: "3"
env:
  VERSION: 0.2.0

tasks:
  default:
    deps: [build]
    cmds:
      - DEBUG=true ./dist/kiosk

  copy-config:
    cmds:
      - cp config.example.yaml config

  build:
    deps: [copy-config]
    cmds:
      - CGO_ENABLED=0 go build -ldflags "-X main.version={{.VERSION}}" -o dist/kiosk .

  docker-image:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --load -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .

  docker-buildx:
    cmds:
      - docker buildx create --name mybuilder --use
      - docker buildx install

  docker-image-push:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --platform linux/amd64,linux/arm64 --push -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .
