version: "3"
env:
  VERSION: 0.14.0-beta.2

includes:
  frontend:
    taskfile: ./taskfile.frontend.yml
    flatten: true

  docker:
    taskfile: ./taskfile.docker.yml
    flatten: true

tasks:
  # Development tasks
  default:
    deps: [build]
    cmds:
      - KIOSK_DEBUG=true ./dist/kiosk

  verbose:
    deps: [build-verbose]
    cmds:
      - KIOSK_DEBUG_VERBOSE=true ./dist/kiosk

  # Backend tasks
  templ:
    cmds:
      - templ generate

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run

  # Build tasks
  build:
    deps: [frontend, templ]
    cmds:
      - go generate *.go
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}}" -o dist/kiosk .

  build-verbose:
    deps: [frontend, templ]
    cmds:
      - go generate *.go
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}} -X github.com/damongolding/immich-kiosk/routes.drawFacesOnImages=true" -o dist/kiosk .

  # Maintenance tasks
  install:
    deps: [update-templ]
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.0
      - go install github.com/psampaz/go-mod-outdated@latest
      - go mod tidy

  outdated:
    cmds:
      - go list -u -m -json all | go-mod-outdated -direct -update
      - cd frontend && pnpm outdated

  update-templ:
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
