version: "3"
env:
  VERSION: 0.13.0-beta.3

tasks:
  # Development tasks
  default:
    deps: [build]
    cmds:
      - KIOSK_DEBUG=true ./dist/kiosk

  verbose:
    deps: [build-verbose]
    cmds:
      - KIOSK_DEBUG_VERBOSE=true ./dist/kiosk

  # Frontend tasks
  frontend:
    deps: [frontend-test, frontend-css, frontend-js]
    dir: ./frontend
    cmds:
      - pnpm lint

  frontend-build:
    dir: ./frontend
    cmds:
      - pnpm build

  frontend-test:
    dir: ./frontend
    cmds:
      - pnpm test

  frontend-css:
    dir: ./frontend
    cmds:
      - pnpm css

  frontend-js:
    dir: ./frontend
    cmds:
      - pnpm js

  # Backend tasks
  templ:
    cmds:
      - templ generate

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run

  # Build tasks
  build:
    deps: [frontend, templ]
    cmds:
      - go generate *.go
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}}" -o dist/kiosk .

  build-verbose:
    deps: [frontend, templ]
    cmds:
      - go generate *.go
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}} -X github.com/damongolding/immich-kiosk/routes.drawFacesOnImages=true" -o dist/kiosk .

  # Docker tasks
  docker-image:
    deps: [build]
    cmds:
      - docker build --no-cache --build-arg VERSION={{.VERSION}} --load -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .

  docker-buildx:
    cmds:
      - docker buildx create --name mybuilder --use
      - docker buildx install

  docker-image-push:
    deps: [build]
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --platform linux/amd64,linux/arm64 --push -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .

  docker-dev-push:
    deps: [build]
    cmds:
      - docker build --build-arg VERSION={{.VERSION}}-DEVELOPMENT --platform linux/amd64,linux/arm64 --push -t damongolding/immich-kiosk-development:{{.VERSION}} -t damongolding/immich-kiosk-development:latest .

  # Maintenance tasks
  outdated:
    cmds:
      - go list -u -m -json all | go-mod-outdated -direct -update
      - cd frontend && pnpm outdated

  update-templ:
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
