version: "3"
env:
  VERSION: 0.10.0
tasks:
  default:
    deps: [build]
    cmds:
      - KIOSK_DEBUG=true ./dist/kiosk

  frontend:
    dir: ./frontend
    cmds:
      - pnpm build

  templ:
    cmds:
      - templ generate

  test:
    cmds:
      - go test ./...

  build:
    deps: [frontend, templ]
    cmds:
      - CGO_ENABLED=0 go build -ldflags "-X main.version={{.VERSION}}" -o dist/kiosk .

  docker-image:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --load -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .

  docker-buildx:
    cmds:
      - docker buildx create --name mybuilder --use
      - docker buildx install

  docker-image-push:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --platform linux/amd64,linux/arm64 --push -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .

  docker-dev-push:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}}-DEVELOPMENT --platform linux/amd64,linux/arm64 --push -t damongolding/immich-kiosk-development:{{.VERSION}} -t damongolding/immich-kiosk-development:latest .

  outdated:
    cmds:
      - go list -m -u all
      - cd frontend && pnpm outdated
