name: Build and Push Docker Image

on:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker buildx build --build-arg VERSION=${{ env.VERSION }} \
          --platform linux/amd64,linux/arm64 \
          --push -t damongolding/immich-kiosk:${{ env.VERSION }} \
          -t damongolding/immich-kiosk:latest .
