name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Get dependencies
        run: go mod download

      - name: Install templ and generate
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate

      - name: Run tests
        env:
          CI: true
        run: |
          mkdir -p test-results
          go test -v ./... > test-results/test.log

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: go-test-results
          path: test-results/test.log

  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'damongolding',
              repo: 'immich-kiosk-unraid',
              event_type: 'generate-xml',
            });
