name: Post to Reddit

on:
  push:
    tags:
      - "v*"

jobs:
  post-release-on-reddit:
    runs-on: ubuntu-latest
    steps:
      - uses: bluwy/release-for-reddit-action@v1
        with:
          username: ${{ secrets.REDDIT_USERNAME }}
          password: ${{ secrets.REDDIT_PASSWORD }}
          app-id: ${{ secrets.REDDIT_APP_ID }}
          app-secret: ${{ secrets.REDDIT_APP_SECRET }}
          subreddit: immich
          title: Immich Kiosk ${{ GITHUB_REF#refs/tags/}} Released
          comment: ${{ github.event.release.body }}
          url: https://github.com/damongolding/immich-kiosk/releases/tag/${{ GITHUB_REF#refs/tags/ }}
